docs: expand command documentation
openupm/openupm-cli pull request #409
Opened 2024-10-02 09:19 UTC by ComradeVanti

This PR expands the command documentation by giving each command or topic it's own file where detailed information can be collected. The relevant file can also be more easily linked.

This doc change also considered what is discussed in #408.

2024-10-03 06:38 UTC, ComradeVanti commented
https://github.com/openupm/openupm-cli/discussions/408#discussioncomment-10819184

Just linking this here, so I dont forget.

2024-10-11 16:54 UTC, ComradeVanti commented
@favoyang you want to proofread me one more time? thanks :)

2024-10-12 14:59 UTC, favoyang requested changes

2024-10-12 14:59 UTC, favoyang commented on docs/help-package-reference.md
> +Example: `com.my.package@latest`
This should be `com.my.package@stable`

2024-10-14 06:41 UTC, ComradeVanti commented on docs/help-package-reference.md
> +Example: `com.my.package@latest`
true. i fixed it

2024-10-14 06:43 UTC, merged